# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
