# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
                ('ages', models.CharField(blank=True, max_length=32, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('last_login_time', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
